---
# Copyright 2016, Rackspace US, Inc.
#
# (C) 2016 Michael Rice <michael.rice@rackspace.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Drop envoy-translator Config(s)
  openstack.config_template.config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ envoy_translator_system_user_name }}"
    group: "{{ envoy_translator_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "envoy-translator.yaml.j2"
      dest: "/etc/envoy-translator/envoy-translator.yaml"
      config_overrides: "{{ envoy_translator_envoy_translator_conf_overrides }}"
      config_type: "yaml"
  notify:
    - Restart envoy-translator services
    - Restart uwsgi services

- name: Drop envoy-translator WSGI Configs
  template:
    src: wsgi.py.j2
    dest: "{{ envoy_translator_bin }}/envoy-translator-api-wsgi"
    owner: "{{ envoy_translator_system_user_name }}"
    group: "{{ envoy_translator_system_group_name }}"
    mode: "0755"
  when: envoy_translator_use_uwsgi | bool
  notify:
    - Restart envoy-translator services
    - Restart uwsgi services
